/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProgramsIndexRouteImport } from './routes/_authenticated/programs/index'
import { Route as AuthenticatedPerformanceIndexRouteImport } from './routes/_authenticated/performance/index'
import { Route as AuthenticatedMealsIndexRouteImport } from './routes/_authenticated/meals/index'
import { Route as AuthenticatedDishesIndexRouteImport } from './routes/_authenticated/dishes/index'
import { Route as AuthenticatedProgramsIdRouteImport } from './routes/_authenticated/programs/$id'
import { Route as AuthenticatedMealsMealIdRouteImport } from './routes/_authenticated/meals/$mealId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDishesCreateRouteImport } from './routes/_authenticated/dishes/create'
import { Route as AuthenticatedDishesIdRouteImport } from './routes/_authenticated/dishes/$id'
import { Route as AuthenticatedDishesSimilarityIndexRouteImport } from './routes/_authenticated/dishes/similarity/index'
import { Route as AuthenticatedMealsMealIdEditRouteImport } from './routes/_authenticated/meals/$mealId/edit'
import { Route as AuthenticatedDishesEditIdRouteImport } from './routes/_authenticated/dishes/edit.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramsIndexRoute =
  AuthenticatedProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceIndexRoute =
  AuthenticatedPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMealsIndexRoute = AuthenticatedMealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDishesIndexRoute =
  AuthenticatedDishesIndexRouteImport.update({
    id: '/dishes/',
    path: '/dishes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramsIdRoute = AuthenticatedProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsMealIdRoute =
  AuthenticatedMealsMealIdRouteImport.update({
    id: '/meals/$mealId',
    path: '/meals/$mealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDishesCreateRoute =
  AuthenticatedDishesCreateRouteImport.update({
    id: '/dishes/create',
    path: '/dishes/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDishesIdRoute = AuthenticatedDishesIdRouteImport.update({
  id: '/dishes/$id',
  path: '/dishes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDishesSimilarityIndexRoute =
  AuthenticatedDishesSimilarityIndexRouteImport.update({
    id: '/dishes/similarity/',
    path: '/dishes/similarity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMealsMealIdEditRoute =
  AuthenticatedMealsMealIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMealsMealIdRoute,
  } as any)
const AuthenticatedDishesEditIdRoute =
  AuthenticatedDishesEditIdRouteImport.update({
    id: '/dishes/edit/$id',
    path: '/dishes/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/dishes/$id': typeof AuthenticatedDishesIdRoute
  '/dishes/create': typeof AuthenticatedDishesCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/meals/$mealId': typeof AuthenticatedMealsMealIdRouteWithChildren
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/dishes': typeof AuthenticatedDishesIndexRoute
  '/meals': typeof AuthenticatedMealsIndexRoute
  '/performance': typeof AuthenticatedPerformanceIndexRoute
  '/programs': typeof AuthenticatedProgramsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/dishes/edit/$id': typeof AuthenticatedDishesEditIdRoute
  '/meals/$mealId/edit': typeof AuthenticatedMealsMealIdEditRoute
  '/dishes/similarity': typeof AuthenticatedDishesSimilarityIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/dishes/$id': typeof AuthenticatedDishesIdRoute
  '/dishes/create': typeof AuthenticatedDishesCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/meals/$mealId': typeof AuthenticatedMealsMealIdRouteWithChildren
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/dishes': typeof AuthenticatedDishesIndexRoute
  '/meals': typeof AuthenticatedMealsIndexRoute
  '/performance': typeof AuthenticatedPerformanceIndexRoute
  '/programs': typeof AuthenticatedProgramsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/dishes/edit/$id': typeof AuthenticatedDishesEditIdRoute
  '/meals/$mealId/edit': typeof AuthenticatedMealsMealIdEditRoute
  '/dishes/similarity': typeof AuthenticatedDishesSimilarityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dishes/$id': typeof AuthenticatedDishesIdRoute
  '/_authenticated/dishes/create': typeof AuthenticatedDishesCreateRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/meals/$mealId': typeof AuthenticatedMealsMealIdRouteWithChildren
  '/_authenticated/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/_authenticated/dishes/': typeof AuthenticatedDishesIndexRoute
  '/_authenticated/meals/': typeof AuthenticatedMealsIndexRoute
  '/_authenticated/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/_authenticated/programs/': typeof AuthenticatedProgramsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/dishes/edit/$id': typeof AuthenticatedDishesEditIdRoute
  '/_authenticated/meals/$mealId/edit': typeof AuthenticatedMealsMealIdEditRoute
  '/_authenticated/dishes/similarity/': typeof AuthenticatedDishesSimilarityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/dishes/$id'
    | '/dishes/create'
    | '/errors/$error'
    | '/meals/$mealId'
    | '/programs/$id'
    | '/dishes'
    | '/meals'
    | '/performance'
    | '/programs'
    | '/users'
    | '/dishes/edit/$id'
    | '/meals/$mealId/edit'
    | '/dishes/similarity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/dishes/$id'
    | '/dishes/create'
    | '/errors/$error'
    | '/meals/$mealId'
    | '/programs/$id'
    | '/dishes'
    | '/meals'
    | '/performance'
    | '/programs'
    | '/users'
    | '/dishes/edit/$id'
    | '/meals/$mealId/edit'
    | '/dishes/similarity'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/dishes/$id'
    | '/_authenticated/dishes/create'
    | '/_authenticated/errors/$error'
    | '/_authenticated/meals/$mealId'
    | '/_authenticated/programs/$id'
    | '/_authenticated/dishes/'
    | '/_authenticated/meals/'
    | '/_authenticated/performance/'
    | '/_authenticated/programs/'
    | '/_authenticated/users/'
    | '/_authenticated/dishes/edit/$id'
    | '/_authenticated/meals/$mealId/edit'
    | '/_authenticated/dishes/similarity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs/': {
      id: '/_authenticated/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance/': {
      id: '/_authenticated/performance/'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals/': {
      id: '/_authenticated/meals/'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dishes/': {
      id: '/_authenticated/dishes/'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof AuthenticatedDishesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs/$id': {
      id: '/_authenticated/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof AuthenticatedProgramsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals/$mealId': {
      id: '/_authenticated/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof AuthenticatedMealsMealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dishes/create': {
      id: '/_authenticated/dishes/create'
      path: '/dishes/create'
      fullPath: '/dishes/create'
      preLoaderRoute: typeof AuthenticatedDishesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dishes/$id': {
      id: '/_authenticated/dishes/$id'
      path: '/dishes/$id'
      fullPath: '/dishes/$id'
      preLoaderRoute: typeof AuthenticatedDishesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dishes/similarity/': {
      id: '/_authenticated/dishes/similarity/'
      path: '/dishes/similarity'
      fullPath: '/dishes/similarity'
      preLoaderRoute: typeof AuthenticatedDishesSimilarityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals/$mealId/edit': {
      id: '/_authenticated/meals/$mealId/edit'
      path: '/edit'
      fullPath: '/meals/$mealId/edit'
      preLoaderRoute: typeof AuthenticatedMealsMealIdEditRouteImport
      parentRoute: typeof AuthenticatedMealsMealIdRoute
    }
    '/_authenticated/dishes/edit/$id': {
      id: '/_authenticated/dishes/edit/$id'
      path: '/dishes/edit/$id'
      fullPath: '/dishes/edit/$id'
      preLoaderRoute: typeof AuthenticatedDishesEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMealsMealIdRouteChildren {
  AuthenticatedMealsMealIdEditRoute: typeof AuthenticatedMealsMealIdEditRoute
}

const AuthenticatedMealsMealIdRouteChildren: AuthenticatedMealsMealIdRouteChildren =
  {
    AuthenticatedMealsMealIdEditRoute: AuthenticatedMealsMealIdEditRoute,
  }

const AuthenticatedMealsMealIdRouteWithChildren =
  AuthenticatedMealsMealIdRoute._addFileChildren(
    AuthenticatedMealsMealIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDishesIdRoute: typeof AuthenticatedDishesIdRoute
  AuthenticatedDishesCreateRoute: typeof AuthenticatedDishesCreateRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMealsMealIdRoute: typeof AuthenticatedMealsMealIdRouteWithChildren
  AuthenticatedProgramsIdRoute: typeof AuthenticatedProgramsIdRoute
  AuthenticatedDishesIndexRoute: typeof AuthenticatedDishesIndexRoute
  AuthenticatedMealsIndexRoute: typeof AuthenticatedMealsIndexRoute
  AuthenticatedPerformanceIndexRoute: typeof AuthenticatedPerformanceIndexRoute
  AuthenticatedProgramsIndexRoute: typeof AuthenticatedProgramsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDishesEditIdRoute: typeof AuthenticatedDishesEditIdRoute
  AuthenticatedDishesSimilarityIndexRoute: typeof AuthenticatedDishesSimilarityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDishesIdRoute: AuthenticatedDishesIdRoute,
  AuthenticatedDishesCreateRoute: AuthenticatedDishesCreateRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMealsMealIdRoute: AuthenticatedMealsMealIdRouteWithChildren,
  AuthenticatedProgramsIdRoute: AuthenticatedProgramsIdRoute,
  AuthenticatedDishesIndexRoute: AuthenticatedDishesIndexRoute,
  AuthenticatedMealsIndexRoute: AuthenticatedMealsIndexRoute,
  AuthenticatedPerformanceIndexRoute: AuthenticatedPerformanceIndexRoute,
  AuthenticatedProgramsIndexRoute: AuthenticatedProgramsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDishesEditIdRoute: AuthenticatedDishesEditIdRoute,
  AuthenticatedDishesSimilarityIndexRoute:
    AuthenticatedDishesSimilarityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
